# Generated by Django 3.2.9 on 2024-02-04 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_contract_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='approval_data',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='稟議'),
        ),
        migrations.AlterField(
            model_name='post',
            name='contract_period_fi',
            field=models.DateField(blank=True, null=True, verbose_name='契約終了日'),
        ),
        migrations.AlterField(
            model_name='post',
            name='contract_period_st',
            field=models.DateField(blank=True, null=True, verbose_name='契約開始日'),
        ),
        migrations.AlterField(
            model_name='post',
            name='order_date',
            field=models.DateField(blank=True, null=True, verbose_name='発注日'),
        ),
        migrations.AlterField(
            model_name='post',
            name='recording_date',
            field=models.DateField(blank=True, null=True, verbose_name='計上予定日'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, '見積依頼済'), (1, '見積確認中'), (2, '発注済'), (3, '計上済')], max_length=20, null=True, verbose_name='ステータス'),
        ),
    ]
